"""Make duration and description non-nullable

Revision ID: 163e6c95055c
Revises: 6a7b43f13f9a
Create Date: 2024-08-07 15:36:07.953320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163e6c95055c'
down_revision = '6a7b43f13f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
