"""relationship consistency

Revision ID: 4e1ff2d00894
Revises: f1895c3bac3e
Create Date: 2024-08-09 12:32:31.646389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1ff2d00894'
down_revision = 'f1895c3bac3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_balance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_balance', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
