"""Add duration to Course and description to Unit as nullable

Revision ID: 6a7b43f13f9a
Revises: 29cacfbd5208
Create Date: 2024-08-07 15:03:41.836019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7b43f13f9a'
down_revision = '29cacfbd5208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(), nullable=True))

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
