"""Allow unique_identifier to be nullable in Transaction

Revision ID: ab6d601d4530
Revises: e24f2aeffea8
Create Date: 2024-08-13 15:48:09.240283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6d601d4530'
down_revision = 'e24f2aeffea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('unique_identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('unique_identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
